---
- type: replace
  path: /instance_groups/name=gogs/jobs/-
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: ((routing-nats-deployment))
    properties:
      route_registrar:
        routes:
        - name: gogs
          port: 8080
          tags:
            component: gogs
          registration_interval: 10s
          uris:
          - ((gogs-uri))

- type: replace
  path: /releases/-
  value:
    name: routing
    version: 0.161.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.161.0
    sha1: 05a4c2c7eac94dca40fb622cc936b8f0271ca04f

# - type: remove
#   path: /properties/gogs/tls_cert
#
# - type: remove
#   path: /properties/gogs/tls_key
#
# - type: remove
#   path: /variables/name=gogs-ca
#
# - type: remove
#   path: /variables/name=gogs-tls
