---
name: gogs

instance_groups:
- name: gogs
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk_type: 1GB
  networks: [{name: default}]
  jobs:
  - name: postgres
    release: gogs
  - name: gogs
    release: gogs

properties:
  gogs:
    password: ((gogs-password))
    tls_cert: ((gogs-tls.certificate))
    tls_key: ((gogs-tls.private_key))
    secret_key: ((gogs-secret-key))
  databases:
    roles:
      - tag: gogs
        name: gogs
        password: ((postgres-password))
    databases:
      - tag: gogs
        name: gogsdb
        citext: true

variables:
- name: postgres-password
  type: password
- name: gogs-secret-key
  type: password
- name: gogs-password
  type: password
- name: gogs-ca
  type: certificate
  options:
    is_ca: true
    common_name: gogsCA
- name: gogs-tls
  type: certificate
  options:
    ca: gogs-ca
    common_name: gogs
    extended_key_usage:
    - client_auth
    - server_auth
    alternative_names:
    - 127.0.0.1
    - "*.gogs.default.gogs.bosh"

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: gogs
  version: 5.1.0
  url: https://github.com/cloudfoundry-community/gogs-boshrelease/releases/download/v5.1.0/gogs-5.1.0.tgz
  sha1: 21bef851d4692f32fa30909c8aa9c3e1b4a07e98
