meta:
  environment: (( merge ))
  dns_root: (( merge ))
  persistent_disk: 4096
  stemcell:
    name: bosh-vsphere-esxi-ubuntu
    version: latest

jobs:
  - name: gogs_z1
    instances: 1
    networks:
    - name: gogs1
      static_ips: (( static_ips(0) ))
    persistent_disk: (( meta.persistent_disk ))

compilation:
  cloud_properties:
    cpu: 1
    ram: 2048
    disk: 18_000

resource_pools:
  - name: small_z1
    cloud_properties:
      cpu: 1
      ram: 2048
      disk: 18_000

networks: (( merge ))
